TEAM-ARK/sprout-backend

- README.md
> Docs : 리드미 수정

- inflearn-back/build.gradle
- inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/Role.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/UserRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/UserService.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
- inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
Validation 애노테이션 사용해 값 검증
Enum타입의 Role 클래스 생성
Builder 패턴 사용(Junit으로 테스트 코드 작성)
현재는 querydsl 사용안하므로 주석처리
> User : 엔티티클래스, 레포지토리 생성

- inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Difficulty.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
> entity 클래스 추가

- inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/course/Course.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/enums/Difficulty.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/enums/Role.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Difficulty.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
- inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
`lecture`와 `review`의 관계를 단방향으로 변경하였습니다. `lecture`에서만 `review`를 참조가능합니다.
> Lecture와 Review 단방향 관계로 변경

- inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
엔티티의 `Validation` 애노테이션을 모두 삭제하였습니다.
`Controller`를 통해 값을 받을 `DTO`를` Validation`하도록 변경하기 위해서입니다. 
추후에 `DTO`를 만들고 `DTO`를 `Validation`하고 이를 통해 엔티티를 생성하도록 하겠습니다.
> etc : Validation 변경

- inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/course/Course.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
- inflearn-back/src/test/java/com/ark/inflearnback/auditing/AuditingTest.java
- inflearn-back/src/test/java/com/ark/inflearnback/domain/lecture/LectureTest.java
- inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
`Lecutre`만 `Builder`를 사용하도록 변경하였습니다. 나머지는 필요한 필드만 파라미터로 받는 생성자를 추가하였습니다.
또한 이는 추후에 파라미터를 하나씩 받는 것이 아닌 `DTO`를 통해 받는 것으로 변경해야합니다.
`Controller`와 `Repository`를 만들고 서비스를 만들어가며 `DTO`를 만들고 그에 따라 변경하면 좋을 듯 합니다.
> feature : 생성자 추가

- inflearn-back/src/main/java/com/ark/inflearnback/domain/category/CategoryRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/course/CourseRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/DiscountRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/HashtagRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/LectureRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtagRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/review/ReviewRepository.java
- inflearn-back/src/main/java/com/ark/inflearnback/domain/video/VideoRepository.java
- inflearn-back/src/test/java/com/ark/inflearnback/domain/lecture/LectureTest.java
- inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
기본적으로 `Spring Data JPA`를 사용하도록 만들었습니다.
`Spring Data JPA`가 정상 적용되었는지 테스트 코드로 검증하였습니다.
이제 기본 틀은 완성되었고 주말에 프론트분들과 회의를 통해 어떤 데이터를 넘겨 받을 것인지 상의 후, 바로 `Controller`를 만들어 `Service`를 구현하면 될 것 같습니다.
> feature : 엔티티별 Repository 생성

- src/main/java/com/ark/inflearnback/config/handler/GlobalRestExceptionHandler.java
- src/main/java/com/ark/inflearnback/config/model/HttpResponse.java
> 초기 설정 누락된 사항 수정보완

- .github/workflows/codeql-analysis.yml
- .github/workflows/gradle-cd.yml
- .github/workflows/gradle-ci.yml
- appspec.yml
[![ARK-2](https://badgen.net/badge/JIRA/ARK-2/0052CC)](https://jira.company.com/browse/ARK-2) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)
* ⚙ CD 테스트 (#37)
* feat: _jira_link.yml
* feat: pr-badge.yml
* refactor: jira-link.yml
* fix: syntax error
* fix: 주석제거
* Update pr-badge.yml
* AIB-5 test
* AIB-5 test
* AIB-5 test
* ARK-1 TEST
* Update pr-badge.yml
* ARK-1 (#32)
* Move pr-badge.yml
* ARK-1
* Create codeql-analysis.yml
* Update gradle.yml
* Update gradle.yml
* feat: spring.properties
* refactor: rename HttpLogCustomRepository.java
* feat: ApplicationTest
* fix: …
> ⚙ CI/CD 테스트 (#39)

- src/main/java/com/ark/inflearnback/domain/security/model/Member.java
- src/main/java/com/ark/inflearnback/domain/security/model/OAuthAttributes.java
- src/main/java/com/ark/inflearnback/domain/security/model/SessionMember.java
- src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
- src/main/resources/application.yml
- src/test/java/com/ark/inflearnback/config/jasypt/JasyptConfigTest.java
[![ARK-3](https://badgen.net/badge/JIRA/ARK-3/0052CC)](https://jira.company.com/browse/ARK-3) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)
구조를 변경하고
단언문 같은 경우에는
`enc` 암호화 문자열이 계속 랜덤값으로 변하여
복화해서 나온 문자열만 테스트로 진행하였습니다.
> Ark 3 - 스프링 시큐리티 Oauth2 구축

- src/main/resources/application.yml
> The OAuth client was not found

- src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
- src/main/resources/application.yml
[![ARK-13](https://badgen.net/badge/JIRA/ARK-13/0052CC)](https://jira.company.com/browse/ARK-13) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)
- 동시 로그인 방지
- 동영상 시청 중 로그아웃 방지
> ARK-13 Session Timeout

- README.md
- build.gradle
- src/main/java/com/ark/inflearnback/configuration/http/model/entity/HttpLog.java
- src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
- src/main/java/com/ark/inflearnback/configuration/security/filter/PermitAllFilter.java
- src/main/java/com/ark/inflearnback/configuration/security/handler/Oauth2AuthenticationSuccessHandler.java
- src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationFailureHandler.java
- src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationSuccessHandler.java
- src/main/java/com/ark/inflearnback/configuration/security/model/entity/Resource.java
- src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
- src/main/resources/static/docs/api/open-api-3.0.1.json
- src/test/java/com/ark/inflearnback/domain/member/controller/MemberApiControllerTest.java
[![ARK-19](https://badgen.net/badge/JIRA/ARK-19/0052CC)](https://jira.company.com/browse/ARK-19) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)
- `API Document` 페이지는 `시스템 관리자` 권한을 가진 사람만 접근 가능하도록 변경
- `API Document` 페이지에 `HTTPS` URI 추가
- `Resource` 객체에서 유니크 인덱스 제거
- Http Method + URI `복합 유니크 인덱스`로 별도 DDL 관리중
- 일부 테스트코드를 현재 코드에 맞게 수정
---
이번 변경사항의 주 목적은 운영환경 HTTPS 구축으로 인한 코드 변경과 운영환경에서의 보안, 테스트를 보완하기 위함입니다.
> ARK-19 시스템 관리자 환경 구축

- deploy.sh
`deploy.sh`, `overwrite.sh`, `rollback.sh` 수정완료!
#147
> hotfix : deploy.sh 수정

- README.md
- module-web/src/main/java/com/ark/sprout/entity/HttpLog.java
- module-web/src/main/java/com/ark/sprout/web/MemberApiController.java
- module-web/src/test/java/com/ark/sprout/web/MemberApiControllerTest.java
[![ARK-34](https://badgen.net/badge/JIRA/ARK-34/0052CC)](https://jira.company.com/browse/ARK-34) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- #172
> ARK-34 나쁜냄새 제거

- module-common/src/main/java/com/ark/sprout/util/LogUtils.java
- module-common/src/test/java/com/ark/sprout/util/LogUtilsTest.java
- module-member/src/main/java/com/ark/sprout/service/MemberService.java
- module-secure/src/main/java/com/ark/sprout/config/SecurityDatabaseInitializer.java
- module-web/src/main/java/com/ark/sprout/entity/HttpLog.java
[![ARK-35](https://badgen.net/badge/JIRA/ARK-35/0052CC)](https://jira.company.com/browse/ARK-35) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
[ARK-35](https://ark-learn-back.atlassian.net//browse/ARK-35)
> ARK-35 로그 컨벤션 정리

- build.gradle
- module-common/src/main/java/com/ark/sprout/util/LogUtils.java
- module-common/src/test/java/com/ark/sprout/util/LogUtilsTest.java
- module-member/src/main/java/com/ark/sprout/service/MemberService.java
- module-secure/src/main/java/com/ark/sprout/config/SecurityDatabaseInitializer.java
- module-secure/src/main/java/com/ark/sprout/service/SecurityResourceService.java
- module-web/src/main/java/com/ark/sprout/entity/HttpLog.java
[![ARK-35](https://badgen.net/badge/JIRA/ARK-35/0052CC)](https://jira.company.com/browse/ARK-35) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- #180 
- `LogUtilsTest` 테스트 케이스 재정의
- `LogUtils` 구현 변경
- 민감정보 기록되던 부분 제거
> ARK-35 로그 컨벤션 정리 (수정)

- build.gradle
- gradle.properties
- module-common/src/main/java/com/ark/sprout/entity/AbstractEntity.java
- module-community-history/build.gradle
- module-community-history/src/main/java/com/ark/sprout/entity/DeleteHistory.java
- module-community-history/src/main/java/com/ark/sprout/entity/EditHistories.java
- module-community-history/src/main/java/com/ark/sprout/entity/EditHistory.java
- module-community-history/src/main/java/com/ark/sprout/repository/DeleteHistoryRepository.java
- module-community-history/src/main/java/com/ark/sprout/repository/EditHistoryRepository.java
- module-community-history/src/main/java/com/ark/sprout/type/ContentType.java
- module-community-history/src/test/java/com/ark/sprout/entity/DeleteHistoryTest.java
- module-community-history/src/test/java/com/ark/sprout/entity/EditHistoriesTest.java
- module-member/src/main/java/com/ark/sprout/entity/Member.java
- settings.gradle
[![ARK-40](https://badgen.net/badge/JIRA/ARK-40/0052CC)](https://jira.company.com/browse/ARK-40) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- #185
> ARK-40 게시판 공통 모듈 추출

- module-secure/src/main/java/com/ark/sprout/config/SecurityConfiguration.java
[![ARK-41](https://badgen.net/badge/JIRA/ARK-41/0052CC)](https://jira.company.com/browse/ARK-41) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- #186
> ARK-41 SameSite=None 임시 설정

- build.gradle
- deploy.sh
- src/main/java/team/ark/sprout/config/DatabaseProperties.java
- src/test/java/team/ark/sprout/config/DevDatabasePropertiesTest.java
- src/test/java/team/ark/sprout/config/ProdDatabasePropertiesTest.java
프로젝트 구조를 모놀리식으로 변경함에 따라 배포 설정도 함께 변경하였다
> 🔥 배포 환경설정 수정

- src/main/resources/application.yaml
- src/main/resources/logback-spring.xml
[![ARK-43](https://badgen.net/badge/JIRA/ARK-43/0052CC)](https://jira.company.com/browse/ARK-43) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- 로그에 하우스키퍼 로그 표현
- 콘솔로그에는 컬러 표현
- 파일로그에는 컬러 제거 (터미널이 지원하지 않는 경우가 존재)
- 로그 보관일 30일->365일로 변경
> :fire: 로그 수정

- deploy.sh
[![ARK-45](https://badgen.net/badge/JIRA/ARK-45/0052CC)](https://jira.company.com/browse/ARK-45) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- 중단배포로 변경
- 8080포트 독립 사용
> :fire: ARK-45 빌드 스크립트 수정

- appspec.yml
- deploy.sh
[![ARK-45](https://badgen.net/badge/JIRA/ARK-45/0052CC)](https://jira.company.com/browse/ARK-45) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
> 🔥  ARK-45 빌드 스크립트 수정(재시도)

- appspec.yml
- deploy.sh
[![ARK-45](https://badgen.net/badge/JIRA/ARK-45/0052CC)](https://jira.company.com/browse/ARK-45) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
> 🔥  ARK-45 빌드 스크립트 수정(최종)

- src/main/java/team/ark/sprout/adapter/out/persistence/AccountMapper.java
- src/main/java/team/ark/sprout/common/config/extension/GitHubOAuth2UserService.java
> :fire: 프로필이미지 가져오는 부분 잘못된 코드 수정

- README.md
- build.gradle
- src/main/resources/application-prod.yaml
- src/main/resources/application.yaml
[![ARK-47](https://badgen.net/badge/JIRA/ARK-47/0052CC)](https://jira.company.com/browse/ARK-47) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- API 문서는 `PRIVATE` 하게 관리한다
> 📝  ARK-47 API 문서를 공개 API에서 제거

- src/main/java/team/ark/sprout/common/config/extension/OAuth2SuccessHandler.java
- src/main/java/team/ark/sprout/common/util/SlackBot.java
- src/main/resources/application.yaml
[![ARK-48](https://badgen.net/badge/JIRA/ARK-48/0052CC)](https://jira.company.com/browse/ARK-48) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- 회원가입 알람 슬랙봇
> :sparkles: ARK-48 신규회원 가입 알림 기능

- build.gradle
- src/main/java/team/ark/sprout/common/config/WebSecurityProdConfig.java
- src/main/resources/application-prod.yaml
[![ARK-49](https://badgen.net/badge/JIRA/ARK-49/0052CC)](https://jira.company.com/browse/ARK-49) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
> ✨ ARK-49 CORS, SameSite 재적용

- README.md
- deploy.sh
- src/main/resources/application.yaml
[![ARK-50](https://badgen.net/badge/JIRA/ARK-50/0052CC)](https://jira.company.com/browse/ARK-50) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=TEAM-ARK&utm_campaign=badge_info)
- README.md 에 프로젝트 정보 추가
- 빌드스크립트에 PID 출력하도록 변경
- 모든 웹 로그를 기록하도록 수정
> 🔥 ARK-50 README, 빌드스크립트, 웹로깅 설정
